<?php


class Model_Comment extends Model
{
    public function get_data()
    {
        parent::get_data(); // TODO: Change the autogenerated stub
    }

    static public function saveComment($data){
       // var_dump($_POST);
        $comment = ORM::for_table('comments')->create();

        $comment->id_task = $data['task_id'];
        $comment->text_comment = $data['text_comment'];
        $comment->comment_date = date('Y-m-d H:i:s');


        $comment->save();

    }
}