<?php


class Model_Task extends Model
{
    public function get_data()
    {
        parent::get_data(); // TODO: Change the autogenerated stub
    }

    public function getTasks(){

        $tasks = ORM::for_table('tasks')->
            join('users', 'tasks.id_user = users.id_user')
            ->order_by_desc('task_date')
            ->find_array();
        return $tasks;
    }
}